### ISSUE TITLE
model.save() not working ?

### ISSUE THREAD

**Issue by redd-gs** [DSD-DBS/py-capellambse#446]
Hello,

I'm very new to this community (and to coding in general) and I just started using capellambse but I already got an issue with model.save(), who seems not to be working (even after reloading my model and everything). 
The modifications seem to be saved in the notebook but not on the capella model.
![image](https://github.com/user-attachments/assets/ad8ff6cd-8d10-44fc-be54-fc7c82ec0516)

What should I do to make it work ?

Thanks a lot !

**Comment by Wuestengecko** [comment]
Hi, and welcome to the community!

The issue isn't with `save()`, but with the fact that this `create()` call doesn't throw an error. `sa.all_functions` is an aggregate list of all functions that exist on that layer. It shouldn't allow you to create new functions directly there, because it's not clear where exactly in the model this function should then be placed (i.e. under which parent function or package).

Due to the bug, this call creates a new function directly below the SA layer object, which makes no sense, so Capella probably just ignores it.

You can instead create the function below the root package (or any other function or function package), for example with:

```python
model.sa.function_package.functions.create(name="Function2")
model.save()
```

After this, Capella should also show this new function in the project explorer.

**Comment by redd-gs** [comment]
Thanks a lot for this quick answer and for your welcoming ! 
Now I have another problem : 
![image](https://github.com/user-attachments/assets/89a570df-d8e8-4bea-8796-257bafcb631a)

I think it expects a parent element but doesn't find one. I've tried to check other solutions but can't seem to find one... Do you know how to proceed to make it work ? Thanks again

**Comment by Wuestengecko** [comment]
Ah, damn it, this is a mess. There's multiple issues at play here, it seems `create()` is broken in more than one way.

Here's an example that should actually work:

```
model.sa.root_function.functions.create(name="Function2")
```

(i.e. use the `root_function` instead of the `function_package`)

I'll look into this in more detail (hopefully) later today.

**Comment by redd-gs** [comment]
Now I  unfortunately have : AttributeError: 'NoneType' object has no attribute 'functions'... I think it has something to do with create() as you said. Thanks for looking into this !

**Comment by Wuestengecko** [comment]
The "list is not coupled" issue with `function_package.functions` should be fixed now. However I'm not sure where you got "AttributeError: 'NoneType' object has no attribute 'functions'" - could you please test that again (it might already be fixed now as well), and if not, post the code that you ran?

**Comment by redd-gs** [comment]
Hi ! Sorry for the late response. I actually tried again with the same code and I still have the same problem as before, which is the "List is not coupled issue". 
I've tried many things to make it right but it still seems that the same problem is remaining....
As for the other code, I was simply trying the root_function method but it doesn't seem to work either : 
![image](https://github.com/user-attachments/assets/19b82d15-97fa-4b19-a12b-023da05b23a5)
